services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: codemind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    devices:
      - "nvidia.com/gpu=all"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  pgdata:
  ollama_data:
    external: true
    name: rag-project_ollama_data
